# Generated by Django 4.1.7 on 2023-03-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location_alter_gallery_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_death',
            field=models.DateField(),
        ),
    ]
