# Generated by Django 4.1.7 on 2023-03-19 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_author_date_birth_alter_author_date_death'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='street',
        ),
        migrations.AlterField(
            model_name='art',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arts', to='api.author'),
        ),
        migrations.AlterField(
            model_name='art',
            name='gallery',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, related_name='arts', to='api.gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='api.location'),
        ),
    ]
