# Generated by Django 4.1.7 on 2023-03-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_gallery_street_alter_art_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='street',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
