# Generated by Django 4.1.7 on 2023-03-19 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_gallery_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_exposition', models.DateField()),
                ('ending_exposition', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='api.author')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='api.gallery')),
            ],
        ),
    ]
