# Generated by Django 4.1.7 on 2023-03-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_gallery_members_galleryauthor_nb_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryauthor',
            name='invited',
            field=models.IntegerField(default=0),
        ),
    ]
