# Generated by Django 4.1.7 on 2023-03-28 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_galleryauthor_invited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='author',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, related_name='arts', to='api.author'),
        ),
    ]
