# Generated by Django 4.1.7 on 2023-04-02 20:27

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_art_author_alter_art_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='year',
            field=models.IntegerField(validators=[api.models.integer_poz_validator]),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_birth',
            field=models.DateField(validators=[api.models.not_current_date]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='capacity',
            field=models.IntegerField(validators=[api.models.capacity_validator]),
        ),
        migrations.AlterField(
            model_name='galleryauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='api.author'),
        ),
        migrations.AlterField(
            model_name='galleryauthor',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='api.gallery'),
        ),
        migrations.AlterField(
            model_name='galleryauthor',
            name='invited',
            field=models.IntegerField(default=0, validators=[api.models.integer_poz_validator]),
        ),
        migrations.AlterField(
            model_name='galleryauthor',
            name='nb_participants',
            field=models.IntegerField(default=0, validators=[api.models.integer_poz_validator]),
        ),
    ]
