# Generated by Django 4.1.7 on 2023-04-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_art_year_alter_author_date_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryauthor',
            name='ending_exposition',
            field=models.DateField(default='2023-04-23'),
        ),
        migrations.AlterField(
            model_name='galleryauthor',
            name='starting_exposition',
            field=models.DateField(default='2023-03-23'),
        ),
    ]
