# Generated by Django 4.1.7 on 2023-04-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_location_to_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_birth',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_death',
            field=models.CharField(max_length=100),
        ),
    ]
